spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/factory_db}
    username: ${SPRING_DATASOURCE_USERNAME:factory}
    password: ${SPRING_DATASOURCE_PASSWORD:factory123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:factory}
    password: ${SPRING_RABBITMQ_PASSWORD:factory123}

server:
  port: 8080
